---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchapikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchapikeys/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchapikeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchroles/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchusers/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - indexlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - indexlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - indexlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - indextemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - indextemplates/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - indextemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - indices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - indices/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - indices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotlifecyclepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotlifecyclepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dashboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dashboards/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dashboards/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - indexpatterns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - indexpatterns/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - indexpatterns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - spaces/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - spaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations/finalizers
  verbs:
  - update
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations/status
  verbs:
  - get
  - patch
  - update
